### ISSUE TITLE
Python 3.12 install fails

### ISSUE THREAD

**Issue by 2sn** [JelteF/PyLaTeX#376]
When I try to install PyLaTeX from pip for Python 3.12, I get the following error:
```
~>pip3 install PyLaTeX
Collecting PyLaTeX
  Using cached PyLaTeX-1.4.1.tar.gz (84 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      /tmp/pip-install-y69k5lf_/pylatex_0cea1b3a06014c4cb04ee6072bf91aba/versioneer.py:418: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "/home/alex/Python/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/alex/Python/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/alex/Python/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-45kbdq4_/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-45kbdq4_/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-45kbdq4_/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-45kbdq4_/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 14, in <module>
        File "/tmp/pip-install-y69k5lf_/pylatex_0cea1b3a06014c4cb04ee6072bf91aba/versioneer.py", line 1476, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/tmp/pip-install-y69k5lf_/pylatex_0cea1b3a06014c4cb04ee6072bf91aba/versioneer.py", line 1408, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-y69k5lf_/pylatex_0cea1b3a06014c4cb04ee6072bf91aba/versioneer.py", line 342, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
I use a Python 3.12 built from source on Fedora 38 Linux

**Comment by A-Little-on-the-Nose** [comment]
`  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      C:\Users\noahs\AppData\Local\Temp\pip-install-9g7vxm_h\pylatex_1316ec183fb54e5da6712cd1bc19ee5a\versioneer.py:418: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\noahs\AppData\Local\Temp\pip-install-9g7vxm_h\pylatex_1316ec183fb54e5da6712cd1bc19ee5a\setup.py", line 14, in <module>
          version = versioneer.get_version()
                    ^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\noahs\AppData\Local\Temp\pip-install-9g7vxm_h\pylatex_1316ec183fb54e5da6712cd1bc19ee5a\versioneer.py", line 1476, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "C:\Users\noahs\AppData\Local\Temp\pip-install-9g7vxm_h\pylatex_1316ec183fb54e5da6712cd1bc19ee5a\versioneer.py", line 1408, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\noahs\AppData\Local\Temp\pip-install-9g7vxm_h\pylatex_1316ec183fb54e5da6712cd1bc19ee5a\versioneer.py", line 342, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

**Comment by JelteF** [comment]
I just published PyLaTeX 1.4.2 which should work fine on Python 3.12
